### ISSUE TITLE
Skip download if already exists

### ISSUE THREAD

**Issue by AlessioDP** [slimjar/slimjar#38]
Some users are reporting me this error:
```
[07:38:39] [Server thread/WARN]: UnresolvedDependencyException{dependency=Dependency{groupId='mysql', artifactId='mysql-connector-java', version='8.0.25', snapshotId='null', transitive=[]}}
[07:38:39] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.lambda$download$0(URLDependencyDownloader.java:64)
[07:38:39] [Server thread/WARN]: 	at java.util.Optional.orElseThrow(Optional.java:290)
[07:38:39] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.download(URLDependencyDownloader.java:64)
[07:38:39] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:45)
[07:38:39] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:56)
[07:38:39] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:50)
[07:38:39] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.build(InjectingApplicationBuilder.java:51)
[07:38:39] [Server thread/WARN]: 	at com.alessiodp.parties.core.common.ADPPlugin.loading(ADPPlugin.java:64)
[07:38:39] [Server thread/WARN]: 	at com.alessiodp.parties.core.bukkit.bootstrap.ADPBukkitBootstrap.onLoad(ADPBukkitBootstrap.java:29)
[07:38:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:297)
[07:38:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198)
[07:38:39] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[07:38:39] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

I think its happening because Maven central was down for some time.
Is it possible to __do not contact Maven central (download)__ if the file has already been downloaded? This will allow servers to work offline if libraries are present.

**Comment by Vshnv** [comment]
Yes, Ill make sure to include this change.

**Comment by yakovliam** [comment]
Please support changing versions as well;
If the version to download has changed, it should download the newest version instead of loading the old

**Comment by Vshnv** [comment]
@yakovliam Could you further explain what you are asking for? Im not sure I understand. Versions are already separated by normal versioning scheme.

**Comment by Vshnv** [comment]
This should be fixed after #39 .
Try release version 1.2.4

**Comment by Lorenzo0111** [comment]
@Vshnv can you release it on the gradle plugins portal?

**Comment by AlessioDP** [comment]
The load still fails in an offline environment:
```
[17:29:47] [Server thread/INFO]: [Parties] Loading libraries of Parties v3.1.9, this may take a while
[17:29:47] [Server thread/WARN]: UnresolvedDependencyException{dependency=Dependency{groupId='mysql', artifactId='mysql-connector-java', version='8.0.25', snapshotId='null', transitive=[]}}
[17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.lambda$download$0(URLDependencyDownloader.java:75)
[17:29:47] [Server thread/WARN]:        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
[17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.download(URLDependencyDownloader.java:75)
[17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:45)
[17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:56)
[17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:50)
[17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.build(InjectingApplicationBuilder.java:56)
[17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.ADPPlugin.loading(ADPPlugin.java:64)
[17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.bukkit.bootstrap.ADPBukkitBootstrap.onLoad(ADPBukkitBootstrap.java:29)
[17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389)
[17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:879)
[17:29:47] [Server thread/WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:651)
[17:29:47] [Server thread/WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
[17:29:47] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764)
[17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:749)
[17:29:47] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:473)
[17:29:47] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:437)
[17:29:47] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200)
[17:29:47] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027)
[17:29:47] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
[17:29:47] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

How to reproduce:
1. Delete library folder and start the plugin in an _online_ environment
2. Go offline
3. Restart server and that error appears

**Comment by yakovliam** [comment]
> The load still fails in an offline environment:
> 
> ```
> [17:29:47] [Server thread/INFO]: [Parties] Loading libraries of Parties v3.1.9, this may take a while
> [17:29:47] [Server thread/WARN]: UnresolvedDependencyException{dependency=Dependency{groupId='mysql', artifactId='mysql-connector-java', version='8.0.25', snapshotId='null', transitive=[]}}
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.lambda$download$0(URLDependencyDownloader.java:75)
> [17:29:47] [Server thread/WARN]:        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.download(URLDependencyDownloader.java:75)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:45)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:56)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:50)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.build(InjectingApplicationBuilder.java:56)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.ADPPlugin.loading(ADPPlugin.java:64)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.bukkit.bootstrap.ADPBukkitBootstrap.onLoad(ADPBukkitBootstrap.java:29)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:879)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:651)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:749)
> [17:29:47] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:473)
> [17:29:47] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:437)
> [17:29:47] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200)
> [17:29:47] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027)
> [17:29:47] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
> [17:29:47] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> ```
> 
> How to reproduce:
> 
> 1. Delete library folder and start the plugin in an _online_ environment
> 2. Go offline
> 3. Restart server and that error appears

I believe that right now SlimJar relies on a dedicated server for some kind of communication. Can you confirm, @Vshnv ?

**Comment by Vshnv** [comment]
> I believe that right now SlimJar relies on a dedicated server for some kind of communication. Can you confirm, @Vshnv ?
Not particularly, You can override the internal central mirrors by providing your own from the current version. ApplicationBuilder# internalRepositories(...)

**Comment by Vshnv** [comment]
> The load still fails in an offline environment:
> 
> ```
> [17:29:47] [Server thread/INFO]: [Parties] Loading libraries of Parties v3.1.9, this may take a while
> [17:29:47] [Server thread/WARN]: UnresolvedDependencyException{dependency=Dependency{groupId='mysql', artifactId='mysql-connector-java', version='8.0.25', snapshotId='null', transitive=[]}}
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.lambda$download$0(URLDependencyDownloader.java:75)
> [17:29:47] [Server thread/WARN]:        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.downloader.URLDependencyDownloader.download(URLDependencyDownloader.java:75)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.helper.InjectionHelper.fetch(InjectionHelper.java:45)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.injectDependencies(SimpleDependencyInjector.java:56)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.injector.SimpleDependencyInjector.inject(SimpleDependencyInjector.java:50)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.addons.external.slimjar.app.builder.InjectingApplicationBuilder.build(InjectingApplicationBuilder.java:56)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.common.ADPPlugin.loading(ADPPlugin.java:64)
> [17:29:47] [Server thread/WARN]:        at com.alessiodp.parties.core.bukkit.bootstrap.ADPBukkitBootstrap.onLoad(ADPBukkitBootstrap.java:29)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:389)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:879)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:651)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:764)
> [17:29:47] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:749)
> [17:29:47] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:473)
> [17:29:47] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:437)
> [17:29:47] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1200)
> [17:29:47] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1027)
> [17:29:47] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307)
> [17:29:47] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
> ```
> 
> How to reproduce:
> 
> 1. Delete library folder and start the plugin in an _online_ environment
> 2. Go offline
> 3. Restart server and that error appears

Are you sure you waited for the initial download to complete?

**Comment by Vshnv** [comment]
Keeping you guys updated..
Found the flaw, seems mysql's SHA-1 hash from central has a newline character appended to it for some reason. Which makes slimjar think that the actual jar was modified so it tried to redownload it. Will release a fix for the same asap.

**Comment by Vshnv** [comment]
Fixed in `1.2.5-SNAPSHOT`. Confirmed from issue author.
